#define MICROPY_HW_BOARD_NAME "ESP32 Dev Board"
#define MICROPY_HW_MCU_NAME "ESP32"
#define MICROPY_HW_BOARD_ESP32_DEV


#define MODULE_CDISPLAY_ENABLED (1)
#define MODULE_SENSOR_ENABLED   (1)
#define MODULE_SWITCH_ENABLED   (1)
