#define MICROPY_HW_BOARD_NAME "KidBright32"
#define MICROPY_HW_MCU_NAME "ESP32"
#define MICROPY_HW_BOARD_KIDBRIGHT32

#define MODULE_CDISPLAY_ENABLED (1)
#define MODULE_SERVO_ENABLED    (1)
#define MODULE_BUZZER_ENABLED   (1)
#define MODULE_RTC_ENABLED      (1)
#define MODULE_USB_ENABLED      (1)
#define MODULE_SENSOR_ENABLED   (1)
#define MODULE_SWITCH_ENABLED   (1)
